springdoc:
  packages-to-scan: com.uscode.alioolio
  swagger-ui.path: /api-docs

  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
spring:
  ai:
    vertex:
      ai:
        gemini:
          project-id: uscode-porject
          location: us-central1
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://34.64.49.231:3306/alioolio_database
    username: root
    password: chrlqlalfqjsgh2@
    driver-class-name: com.mysql.cj.jdbc.Driver
    task:
      scheduling:
        pool:
          size=5:

cors:
  origins: http://localhost:3000,https://dreamfarm.im,https://www.dreamfarm.im
  domain: .dreamfarm.im