name: Java CI with Gradle Docker

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/alioolio:latest .
          docker push ${{ secrets.DOCKER_REPO }}/alioolio

      - name: Deploy
        run: |
          docker stop uscode-server  || true
          docker rm -f uscode-server  || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker pull ${{ secrets.DOCKER_REPO }}/alioolio:latest
          docker run -v /var/log/service:/var/log/service  --name uscode-server -p 8080:8080 --network=uscode-network -d --restart unless-stopped ${{ secrets.DOCKER_REPO }}/alioolio:latest